wmrc notify library

diff --git a/src/HOME/.config/wmrc/modules/screen/backlight b/src/HOME/.config/wmrc/modules/screen/backlight
--- a/src/HOME/.config/wmrc/modules/screen/backlight
+++ b/src/HOME/.config/wmrc/modules/screen/backlight
@@ -2,134 +2,167 @@
 
 export WMRC_DEPENDENCIES='sudo ddcutil'
 
-INTERNAL_VENDOR="$(find /sys/class/backlight/ -mindepth 1 -maxdepth 1 -printf '%P' | head -n 1)"
+vendor="$(find /sys/class/backlight/ -mindepth 1 -maxdepth 1 -printf '%P' | head -n 1)"
+current="/sys/class/backlight/$vendor/brightness"
 
-MAX_FILE="/sys/class/backlight/$INTERNAL_VENDOR/max_brightness"
-CUR_FILE="/sys/class/backlight/$INTERNAL_VENDOR/brightness"
+init() {
+  if sudo modprobe i2c-dev; then
+    info "Loaded I2C kernel module"
+  else
+    error "Unable to load I2C kernel module"
+    return 1
+  fi
+}
 
 is_internal() {
-  if [ -f "$MAX_FILE" ] && [ -f "$CUR_FILE" ]; then
-    return 0 # Intel backlight
+  if [ -f "$current" ]; then
+    return 0
   else
     return 1 # external monitor
   fi
 }
 
-read() {
-
+equ() {
   if is_internal; then
-    [ -f "$MAX_FILE" ] && [ -f "$CUR_FILE" ] || \
-      {
-        error "Brightness control is unavailable!"
-        exit 2
-      }
-
-    sudo -v >/dev/null || \
-      {
-        error "User '$(whoami)' is not allowed to run sudo!"
-        exit 3
-      }
-
-    MAX="$(cat "$MAX_FILE")"
-    CUR="$(cat "$CUR_FILE")"
-
-  else
-
-    sudo modprobe i2c-dev || \
-      {
-        error "Unable to load I2C kernel module!"
-        exit 4
-      }
-
-    CUR="$(sudo ddcutil getvcp 10 | grep -Po 'current value *= *\K.*?(?=,)')"
-    MAX="$(sudo ddcutil getvcp 10 | grep -Po 'max value *= *\K.*?(?=$)')"
-
-    [ "$CUR" != '' ] && [ "$MAX" != '' ] || \
-      {
-        error "Unable to read brigthness values!"
-        exit 2
-      }
-
+    xbacklight -set "${1:-100}"
   fi
-
-}
-
-step() {
-
-  STEP=$(( CUR * CUR / MAX / 33))
-  [ "$STEP" = "0" ] && \
-    STEP="1"
-
-  echo "$STEP"
-
-}
-
-write() {
-
-  read
-
-  NEW="$1"
-
-  [ "$NEW" -gt "$MAX" ] && \
-    NEW="$MAX"
-
-  [ "$NEW" -lt "0" ] && \
-    NEW="0"
-
-  if is_internal; then
-
-    debug 'Internal monitor'
-    echo "$NEW" | sudo tee "$CUR_FILE"
-
-  else
-
-    debug 'External I2C monitor'
-    sudo ddcutil setvcp 10 "$NEW"
-
-  fi
-
 }
 
 inc() {
-
-  read
-  step
-
-  [ -z "$2" ] && \
-    MUL=1 || MUL="$2"
-
-  CUR=$(( CUR + STEP * MUL ))
-
-  info 'Increase monitor backlight' "$CUR"
-  write "$CUR"
-
+  if is_internal; then
+    xbacklight -inc 1 #"${1:-1}"
+  fi
 }
 
 dec() {
-
-  read
-  step
-
-  [ -z "$2" ] && \
-    MUL=1 || MUL="$2"
-
-  CUR=$(( CUR - STEP * MUL ))
-
-  info 'Decrease monitor backlight' "$CUR"
-  write "$CUR"
-
+  if is_internal; then
+    xbacklight -dec 1 #"${1:-1}"
+  fi
 }
 
-equ() {
+# INTERNAL_VENDOR=
 
-  read
+# MAX_FILE="/sys/class/backlight/$INTERNAL_VENDOR/max_brightness"
+# CUR_FILE="/sys/class/backlight/$INTERNAL_VENDOR/brightness"
 
-  [ -z "$2" ] && \
-    MUL=1 || MUL="$2"
 
-  CUR=$(( MAX / 100 * MUL ))
 
-  info 'Set monitor backlight' "$CUR"
-  write "$CUR"
+# read() {
 
-}
+#   if is_internal; then
+#     [ -f "$MAX_FILE" ] && [ -f "$CUR_FILE" ] || \
+#       {
+#         error "Brightness control is unavailable!"
+#         exit 2
+#       }
+
+#     sudo -v >/dev/null || \
+#       {
+#         error "User '$(whoami)' is not allowed to run sudo!"
+#         exit 3
+#       }
+
+#     MAX="$(cat "$MAX_FILE")"
+#     CUR="$(cat "$CUR_FILE")"
+
+#   else
+
+#     sudo modprobe i2c-dev || \
+#       {
+#         error "Unable to load I2C kernel module!"
+#         exit 4
+#       }
+
+#     CUR="$(sudo ddcutil getvcp 10 | grep -Po 'current value *= *\K.*?(?=,)')"
+#     MAX="$(sudo ddcutil getvcp 10 | grep -Po 'max value *= *\K.*?(?=$)')"
+
+#     [ "$CUR" != '' ] && [ "$MAX" != '' ] || \
+#       {
+#         error "Unable to read brigthness values!"
+#         exit 2
+#       }
+
+#   fi
+
+# }
+
+# step() {
+
+#   STEP=$(( CUR * CUR / MAX / 33))
+#   [ "$STEP" = "0" ] && \
+#     STEP="1"
+
+#   echo "$STEP"
+
+# }
+
+# write() {
+
+#   read
+
+#   NEW="$1"
+
+#   [ "$NEW" -gt "$MAX" ] && \
+#     NEW="$MAX"
+
+#   [ "$NEW" -lt "0" ] && \
+#     NEW="0"
+
+#   if is_internal; then
+
+#     debug 'Internal monitor'
+#     #echo "$NEW" | sudo tee "$CUR_FILE"
+#     xbacklight -set "$CUR"
+
+#   else
+
+#     debug 'External I2C monitor'
+#     sudo ddcutil setvcp 10 "$NEW"
+
+#   fi
+
+# }
+
+# inc() {
+
+#   read
+#   step
+
+#   [ -z "$2" ] && \
+#     MUL=1 || MUL="$2"
+
+#   CUR=$(( CUR + STEP * MUL ))
+
+#   info 'Increase monitor backlight' "$CUR"
+#   write "$CUR"
+
+# }
+
+# dec() {
+
+#   read
+#   step
+
+#   [ -z "$2" ] && \
+#     MUL=1 || MUL="$2"
+
+#   CUR=$(( CUR - STEP * MUL ))
+
+#   info 'Decrease monitor backlight' "$CUR"
+#   write "$CUR"
+
+# }
+
+# equ() {
+
+#   read
+
+#   [ -z "$2" ] && \
+#     MUL=1 || MUL="$2"
+
+#   CUR=$(( MAX / 100 * MUL ))
+
+#   info 'Set monitor backlight' "$CUR"
+#   write "$CUR"
+
+# }
