improve old wmrc modules

diff --git a/src/HOME/.config/wmrc/modules/screen/backlight b/src/HOME/.config/wmrc/modules/screen/backlight
--- a/src/HOME/.config/wmrc/modules/screen/backlight
+++ b/src/HOME/.config/wmrc/modules/screen/backlight
@@ -1,168 +1,123 @@
 #!/bin/sh
 
 export WMRC_DEPENDENCIES='sudo ddcutil'
+export _module
 
-vendor="$(find /sys/class/backlight/ -mindepth 1 -maxdepth 1 -printf '%P' | head -n 1)"
-current="/sys/class/backlight/$vendor/brightness"
+WMRC_BACKLIGHT_DEFAULT="${WMRC_BACKLIGHT_DEFAULT:-100}"
+WMRC_BACKLIGHT_STEP="${WMRC_BACKLIGHT_STEP:-10}"
+
+internal_vendor="$(find /sys/class/backlight/ -mindepth 1 -maxdepth 1 -printf '%P' | head -n 1)"
+internal_file="/sys/class/backlight/$internal_vendor/brightness"
+external_file="/tmp/wmrc::$(echo "$_module" | sed 's,/,::,g')@$(whoami)${DISPLAY}.brightness"
 
 init() {
-  if sudo modprobe i2c-dev; then
-    info "Loaded I2C kernel module"
-  else
-    error "Unable to load I2C kernel module"
-    return 1
-  fi
+    if lsmod | grep -q i2c_dev; then
+        info "Already loaded I2C kernel module"
+    elif sudo modprobe i2c-dev; then
+        info "Loaded I2C kernel module"
+    else
+        error "Unable to load I2C kernel module"
+        return 1
+    fi
+    if has_monitor internal; then
+        info 'Detected internal monitor' "$internal_vendor"
+    fi
+    if detect_external external; then
+        info 'Detected external monitor'
+        ddcutil_read
+    else
+        rm -f "$external_file"
+    fi
 }
 
-is_internal() {
-  if [ -f "$current" ]; then
-    return 0
-  else
-    return 1 # external monitor
-  fi
+has_monitor() {
+    _file="$(eval "$(printf 'echo $%s_file' "${1:-internal}")")"
+    if [ -f "$_file" ]; then
+        return 0
+    else
+        return 1
+    fi
 }
 
-equ() {
-  if is_internal; then
-    xbacklight -set "${1:-100}"
-  fi
+detect_external() {
+    if ddcutil detect | grep -q '^Display'; then
+        return 0
+    else
+        return 1
+    fi
 }
 
-inc() {
-  if is_internal; then
-    xbacklight -inc 1 #"${1:-1}"
-  fi
+set_to() {
+    _value="${1:-$WMRC_BACKLIGHT_DEFAULT}"
+    if has_monitor internal && [ "$2" != 'external' ]; then
+        xbacklight -set "$_value"
+        info 'Set internal backlight' "$_value"
+    fi
+    if has_monitor external && [ "$2" != 'internal' ]; then
+        if ddcutil_write "$_value"; then
+            info 'Set external backlight' "$_value"
+        else
+            error 'Failed to set external backlight'
+        fi
+    fi
 }
 
-dec() {
-  if is_internal; then
-    xbacklight -dec 1 #"${1:-1}"
-  fi
+increase() {
+    _step="${1:-$WMRC_BACKLIGHT_STEP}"
+    if has_monitor internal && [ "$2" != 'external' ]; then
+        xbacklight -inc "$_step"
+        info 'Increase internal backlight' "$(xbackglight -get)"
+    fi
+    if has_monitor external && [ "$2" != 'internal' ]; then
+        _current="$(cat "$external_file")"
+        _current="$((_current+_step))"
+        if ddcutil_write "$_current"; then
+            info 'Increased external backlight' "$_current"
+        else
+            error 'Failed to increase external backlight' "$_current"
+            ddcutil_read
+        fi
+    fi
 }
 
-# INTERNAL_VENDOR=
+decrease() {
+    _step="${1:-$WMRC_BACKLIGHT_STEP}"
+    if has_monitor internal && [ "$2" != 'external' ]; then
+        xbacklight -dec "$_step"
+        info 'Decrease internal backlight' "$(xbackglight -get)"
+    fi
+    if has_monitor external && [ "$2" != 'internal' ]; then
+        _current="$(cat "$external_file")"
+        _current="$((_current-_step))"
+        if ddcutil_write "$_current"; then
+            info 'Decreased external backlight' "$_current"
+        else
+            error 'Failed to decrease external backlight' "$_current"
+            ddcutil_read
+        fi
+    fi
+}
 
-# MAX_FILE="/sys/class/backlight/$INTERNAL_VENDOR/max_brightness"
-# CUR_FILE="/sys/class/backlight/$INTERNAL_VENDOR/brightness"
+ddcutil_write() {
+    if [ "$1" -gt 100 ] || [ "$1" -lt 0 ]; then
+        warn 'External backlight value reached the limit'
+        return 0
+    fi
+    if ! daemon_get_pid; then
+        ddcutil setvcp 10 "$1" &
+        _ddcutil_pid="$!"
+        daemon_set_pid "$_ddcutil_pid"
+        if wait "$_ddcutil_pid"; then
+             echo "$1" > "$external_file"
+        else
+            return 1
+        fi
+    fi
+}
 
-
-
-# read() {
-
-#   if is_internal; then
-#     [ -f "$MAX_FILE" ] && [ -f "$CUR_FILE" ] || \
-#       {
-#         error "Brightness control is unavailable!"
-#         exit 2
-#       }
-
-#     sudo -v >/dev/null || \
-#       {
-#         error "User '$(whoami)' is not allowed to run sudo!"
-#         exit 3
-#       }
-
-#     MAX="$(cat "$MAX_FILE")"
-#     CUR="$(cat "$CUR_FILE")"
-
-#   else
-
-#     sudo modprobe i2c-dev || \
-#       {
-#         error "Unable to load I2C kernel module!"
-#         exit 4
-#       }
-
-#     CUR="$(sudo ddcutil getvcp 10 | grep -Po 'current value *= *\K.*?(?=,)')"
-#     MAX="$(sudo ddcutil getvcp 10 | grep -Po 'max value *= *\K.*?(?=$)')"
-
-#     [ "$CUR" != '' ] && [ "$MAX" != '' ] || \
-#       {
-#         error "Unable to read brigthness values!"
-#         exit 2
-#       }
-
-#   fi
-
-# }
-
-# step() {
-
-#   STEP=$(( CUR * CUR / MAX / 33))
-#   [ "$STEP" = "0" ] && \
-#     STEP="1"
-
-#   echo "$STEP"
-
-# }
-
-# write() {
-
-#   read
-
-#   NEW="$1"
-
-#   [ "$NEW" -gt "$MAX" ] && \
-#     NEW="$MAX"
-
-#   [ "$NEW" -lt "0" ] && \
-#     NEW="0"
-
-#   if is_internal; then
-
-#     debug 'Internal monitor'
-#     #echo "$NEW" | sudo tee "$CUR_FILE"
-#     xbacklight -set "$CUR"
-
-#   else
-
-#     debug 'External I2C monitor'
-#     sudo ddcutil setvcp 10 "$NEW"
-
-#   fi
-
-# }
-
-# inc() {
-
-#   read
-#   step
-
-#   [ -z "$2" ] && \
-#     MUL=1 || MUL="$2"
-
-#   CUR=$(( CUR + STEP * MUL ))
-
-#   info 'Increase monitor backlight' "$CUR"
-#   write "$CUR"
-
-# }
-
-# dec() {
-
-#   read
-#   step
-
-#   [ -z "$2" ] && \
-#     MUL=1 || MUL="$2"
-
-#   CUR=$(( CUR - STEP * MUL ))
-
-#   info 'Decrease monitor backlight' "$CUR"
-#   write "$CUR"
-
-# }
-
-# equ() {
-
-#   read
-
-#   [ -z "$2" ] && \
-#     MUL=1 || MUL="$2"
-
-#   CUR=$(( MAX / 100 * MUL ))
-
-#   info 'Set monitor backlight' "$CUR"
-#   write "$CUR"
-
-# }
+ddcutil_read() {
+    if ! daemon_get_pid; then
+        daemon_set_pid "$$"
+        ddcutil getvcp 10 | grep -Po 'current value *= *\K.*?(?=,)' > "$external_file"
+    fi
+}
