restore error panic handling

diff --git a/src/HOME/.config/wmrc/modules/screen/backlight b/src/HOME/.config/wmrc/modules/screen/backlight
--- a/src/HOME/.config/wmrc/modules/screen/backlight
+++ b/src/HOME/.config/wmrc/modules/screen/backlight
@@ -19,10 +19,16 @@ read() {
 
   if is_internal; then
     [ -f "$MAX_FILE" ] && [ -f "$CUR_FILE" ] || \
-      error "Brightness control is unavailable!" fatal 2
+      {
+        error "Brightness control is unavailable!"
+        exit 2
+      }
 
     sudo -v >/dev/null || \
-      error "User '$(whoami)' is not allowed to run sudo!" fatal 3
+      {
+        error "User '$(whoami)' is not allowed to run sudo!"
+        exit 3
+      }
 
     MAX="$(cat "$MAX_FILE")"
     CUR="$(cat "$CUR_FILE")"
@@ -30,13 +36,19 @@ read() {
   else
 
     sudo modprobe i2c-dev || \
-      error "Unable to load I2C kernel module!" fatal 4
+      {
+        error "Unable to load I2C kernel module!"
+        exit 4
+      }
 
     CUR="$(sudo ddcutil getvcp 10 | grep -Po 'current value *= *\K.*?(?=,)')"
     MAX="$(sudo ddcutil getvcp 10 | grep -Po 'max value *= *\K.*?(?=$)')"
 
     [ "$CUR" != '' ] && [ "$MAX" != '' ] || \
-      error "Unable to read brigthness values!" fatal 2
+      {
+        error "Unable to read brigthness values!"
+        exit 2
+      }
 
   fi
 
diff --git a/src/HOME/.config/wmrc/modules/screen/wallpaper b/src/HOME/.config/wmrc/modules/screen/wallpaper
--- a/src/HOME/.config/wmrc/modules/screen/wallpaper
+++ b/src/HOME/.config/wmrc/modules/screen/wallpaper
@@ -5,8 +5,10 @@ export WMRC_DEPENDENCIES='feh'
 start() {
 
   BCK_IMG="$HOME/Pictures/wallpaper.png"
-  [ -f "$BCK_IMG" ] || \
-    error "Wallpaper image '$BCK_IMG' is missing!" fatal 2
+  if ! [ -f "$BCK_IMG" ]; then
+    error "Wallpaper image '$BCK_IMG' is missing!"
+    exit 2
+  fi
 
   DISPLAY=$DISPLAY feh --bg-fill "$BCK_IMG"
 
diff --git a/src/HOME/.config/wmrc/modules/screen/wallpaper_dynamic b/src/HOME/.config/wmrc/modules/screen/wallpaper_dynamic
--- a/src/HOME/.config/wmrc/modules/screen/wallpaper_dynamic
+++ b/src/HOME/.config/wmrc/modules/screen/wallpaper_dynamic
@@ -7,16 +7,22 @@ COMPOSITE="convert -colorspace Gray \( $BCK_IMG -evaluate multiply %.2f \) \( $B
 DELAY=$((5*60))
 
 PID_FILE="/tmp/dynamic_wallpaper_daemon@$(whoami)"
-LATLNG="$(echo "$LOCATION" | sed 's|_|.|g; s|N|?lat=|; s|S|\&lng=|;')"
+LATLNG="$(echo "$WMRC_LOCATION" | sed 's|_|.|g; s|N|?lat=|; s|S|\&lng=|;')"
 
 start() {
 
 
 	[ -f "$(printf "$BCK_IMG" 'day')" ] && [ -f "$(printf "$BCK_IMG" 'night')" ] || \
-    	error "Wallpaper images are missing!" fatal 2
+    	{
+			error "Wallpaper images are missing!"
+			exit 2
+		}
 
     [ -f "$PID_FILE" ] && ps "$(cat "$PID_FILE")" >/dev/null && \
-    	error "Dynamic wallpaper daemon is already running!" fatal 3
+    	{
+			error "Dynamic wallpaper daemon is already running!"
+			exit 3
+		}
 
 	daemon &
 
@@ -32,7 +38,10 @@ stop() {
   PID="$(cat "$PID_FILE")"
 
   ps "$PID" >/dev/null ||
-    error "Dynamic wallpaper daemon is not running!" fatal 4
+    {
+		error "Dynamic wallpaper daemon is not running!"
+		exit 4
+	}
 
   kill -9 "$PID"
 
@@ -42,6 +51,7 @@ daemon() {
 
 	while true; do
 
+		info "Setting dynamic wallpaper"
 		api
 		background
 		sleep "$DELAY"
@@ -60,6 +70,9 @@ api() {
 		sunrise="$(echo "$api_response" | jq -r '.results.sunrise' | xargs date +%s -d)"
 		sunset="$(echo "$api_response" | jq -r '.results.sunset' | xargs date +%s -d)"
 	fi
+
+	debug 'Sunrise' "$sunrise"
+	debug 'Sunset' "$sunset"
 
 }
 
@@ -87,7 +100,7 @@ background() {
 	case "$part" in
 		'night'|'day')
 			command="$(printf "DISPLAY=$DISPLAY feh --bg-fill $BCK_IMG\n" "$part")";
-			break;;
+			;;
 		'sunrise')
 			day_mul="$(echo "scale=2;($now-($sunrise-$fade_period/2))/$fade_period" | bc)";
 			night_mul="$(echo "scale=2;(1-$day_mul)" | bc)";
@@ -97,7 +110,7 @@ background() {
 				"/tmp/dynamic_wallpaper.$USER.png" \
 				"/tmp/dynamic_wallpaper.$USER.png"
 			)";
-			break;;
+			;;
 		'sunset')
 			night_mul="$(echo "scale=2;($now-($sunset-$fade_period/2))/$fade_period" | bc)";
 			day_mul="$(echo "scale=2;(1-$night_mul)" | bc)";
@@ -107,7 +120,7 @@ background() {
 				"/tmp/dynamic_wallpaper.$USER.png" \
 				"/tmp/dynamic_wallpaper.$USER.png"
 			)";
-			break;;
+			;;
 	esac
 
 	eval "$command"
