improve wmrc module logging and daemons

diff --git a/src/HOME/.config/wmrc/modules/screen/wallpaper_dynamic b/src/HOME/.config/wmrc/modules/screen/wallpaper_dynamic
--- a/src/HOME/.config/wmrc/modules/screen/wallpaper_dynamic
+++ b/src/HOME/.config/wmrc/modules/screen/wallpaper_dynamic
@@ -6,97 +6,59 @@ BCK_IMG="$HOME/Pictures/wallpaper-%s.png"
 COMPOSITE="convert -colorspace Gray \( $BCK_IMG -evaluate multiply %.2f \) \( $BCK_IMG -evaluate multiply %.2f \) -compose plus -composite %s"
 DELAY=$((5*60))
 
-PID_FILE="/tmp/dynamic_wallpaper_daemon@$(whoami)"
 LATLNG="$(echo "$WMRC_LOCATION" | sed 's|_|.|g; s|N|?lat=|; s|S|\&lng=|;')"
 
 start() {
-
-
-	[ -f "$(printf "$BCK_IMG" 'day')" ] && [ -f "$(printf "$BCK_IMG" 'night')" ] || \
-    	{
-			error "Wallpaper images are missing!"
-			exit 2
-		}
-
-    [ -f "$PID_FILE" ] && ps "$(cat "$PID_FILE")" >/dev/null && \
-    	{
-			error "Dynamic wallpaper daemon is already running!"
-			exit 3
-		}
-
-	daemon &
-
-	echo $! > "$PID_FILE"
-
-}
-
-stop() {
-
-  [ -f "$PID_FILE" ] ||
-    exit
-
-  PID="$(cat "$PID_FILE")"
-
-  ps "$PID" >/dev/null ||
-    {
-		error "Dynamic wallpaper daemon is not running!"
-		exit 4
-	}
-
-  kill -9 "$PID"
-
+	if ! test -f "$(printf "$BCK_IMG" 'day')" || ! test -f "$(printf "$BCK_IMG" 'night')"; then
+		error "Wallpaper images are missing!"
+		return 1
+	fi
+	if daemon_get_pid; then
+		error "Dynamic wallpaper daemon is already running!"
+		return 1
+	else
+		daemon &
+		daemon_set_pid "$!"
+	fi
 }
 
 daemon() {
-
 	while true; do
-
-		info "Setting dynamic wallpaper"
 		api
 		background
 		sleep "$DELAY"
-
+		debug "Next wallpaper" "$DELAY seconds"
 	done
-
 }
 
 api() {
-
 	api_new_date="$(date -u +%D)"
-
 	if [ "$api_response" = '' ] || [ "$api_new_date" != "$api_date" ]; then
 		api_date="$api_new_date"
 		api_response="$(curl --silent "https://api.sunrise-sunset.org/json$LATLNG&formatted=0")"
 		sunrise="$(echo "$api_response" | jq -r '.results.sunrise' | xargs date +%s -d)"
 		sunset="$(echo "$api_response" | jq -r '.results.sunset' | xargs date +%s -d)"
 	fi
-
 	debug 'Sunrise' "$sunrise"
 	debug 'Sunset' "$sunset"
-
 }
 
 background() {
-
 	fade_period=3600
-
 	now="$(date -u +%s)"
-
 	part='night'
-	if [ $now -gt $((sunset - fade_period / 2)) ]; then
-		if [ $now -lt $((sunset + fade_period / 2)) ]; then
+	if [ "$now" -gt $((sunset - fade_period / 2)) ]; then
+		if [ "$now" -lt $((sunset + fade_period / 2)) ]; then
 			part='sunset'
 		fi
-	elif [ $now -gt $((sunrise - fade_period / 2)) ]; then
-		if [ $now -lt $((sunrise + fade_period / 2)) ]; then
+	elif [ "$now" -gt $((sunrise - fade_period / 2)) ]; then
+		if [ "$now" -lt $((sunrise + fade_period / 2)) ]; then
 			part='sunrise'
 		else
 			part='day'
 		fi
 	fi
-
 	command=''
-
 	case "$part" in
 		'night'|'day')
 			command="$(printf "DISPLAY=$DISPLAY feh --bg-fill $BCK_IMG\n" "$part")";
@@ -104,6 +66,8 @@ background() {
 		'sunrise')
 			day_mul="$(echo "scale=2;($now-($sunrise-$fade_period/2))/$fade_period" | bc)";
 			night_mul="$(echo "scale=2;(1-$day_mul)" | bc)";
+			debug "Day multiplier" "$day_mul"
+			debug "Night multiplier" "$day_mul"
 			command="$(
 				printf "$COMPOSITE && DISPLAY=$DISPLAY feh --bg-fill %s" \
 				'day' "$day_mul" 'night' "$night_mul" \
@@ -114,6 +78,8 @@ background() {
 		'sunset')
 			night_mul="$(echo "scale=2;($now-($sunset-$fade_period/2))/$fade_period" | bc)";
 			day_mul="$(echo "scale=2;(1-$night_mul)" | bc)";
+			debug "Day multiplier" "$day_mul"
+			debug "Night multiplier" "$day_mul"
 			command="$(
 				printf "$COMPOSITE && DISPLAY=$DISPLAY feh --bg-fill %s" \
 				'day' "$day_mul" 'night' "$night_mul" \
@@ -122,7 +88,6 @@ background() {
 			)";
 			;;
 	esac
-
+	info "Setting dynamic wallpaper" "$part"
 	eval "$command"
-
 }
