bspwmrc dependency check

diff --git a/home/filiparag/.config/bspwm/bspwmrc b/home/filiparag/.config/bspwm/bspwmrc
--- a/home/filiparag/.config/bspwm/bspwmrc
+++ b/home/filiparag/.config/bspwm/bspwmrc
@@ -3,20 +3,68 @@
 export WM="bspwm"
 
 MODULES="$(dirname "$0")/modules"
+RC_CONF="$MODULES/rc.conf"
 
+CONFIG_DISP_ERR="$(grep -Pzo '\%display_errors += +\K(true|false)' "$RC_CONF"  | tr '\0' '\n')"
+CONFIG_DP_CHECK="$(grep -Pzo '\%dependency_check += +\K(true|false)' "$RC_CONF"  | tr '\0' '\n')"
+
+CRITICAL_ERROR=0
 function error_message {
-	$MODULES/interface/notify error "$1"
-	printf "$1\n" | sed 's:<i>::g; s:</i>::g' >&2
-	exit 1
+	if [[ "$CONFIG_DISP_ERR" != "false" ]]; then
+		$MODULES/interface/notify error "$1"
+	fi
+	if [[ "$2" == "abort" ]]; then
+		exit 1
+	elif [[ "$2" == "critical" ]]; then
+		CRITICAL_ERROR=1
+	fi
+}
+
+UNMET_DEPS=""
+function check_dependencies {
+
+	DEPENDENCY_ERROR=0
+
+	# Check if all dependencies are in PATH
+	for DEPENDENCY in $(grep -Po '(?<=DEPENDENCIES:)(( *[-\/_a-zA-Z0-9]+, *)*( *[-\/_a-zA-Z0-9]+)+)' "$MODULES/$1"); do
+		DEP=$(printf "$DEPENDENCY" | sed 's/,//g; s/ //g')
+		if ! which "$DEP" &> /dev/null; then
+			error_message "Command '<i>$DEP</i>' required by module '<i>$1</i>' was not found in '\$PATH!'" "critical"
+			DEPENDENCY_ERROR=1
+			UNMET_DEPS="$UNMET_DEPS$DEPENDENCY\n"
+		fi
+	done
+
+	# Recursively check submodule dependencies
+	for SUBMODULE in $(cat "$MODULES/$1" | sed 's/#.*//g' | grep -Po '(?<=\$MODULES\/)([-_a-zA-Z0-9]+\/[-._a-zA-Z0-9\*]+)'); do
+		if [ ! -f "$MODULES/$SUBMODULE" ]; then
+			error_message "Submodule '<i>$SUBMODULE</i>' required by '<i>$1</i>' was not found!" "critical"
+			DEPENDENCY_ERROR=1
+		else
+			if [ ! -x "$MODULES/$SUBMODULE" ]; then
+				chmod +x "$MODULES/$SUBMODULE"
+			fi
+			check_dependencies "$SUBMODULE"
+		fi
+	done
+
+	return $DEPENDENCY_ERROR
+
 }
 
 MODE="start"
-RC_CONF="$MODULES/rc.conf"
 
 if [ "$1" == "--dry-run" ]; then
 	if [ -n "$2" ]; then
 		MODE="$2"
 	fi
+elif [ "$1" == "--unmet-deps" ]; then
+	for MOD in $(find "$MODULES" -type f -not -path "$MODULES/rc.conf" -printf "%P\n"); do
+		check_dependencies $MOD
+	done
+	UNMET_DEPS=$(printf "$UNMET_DEPS" | awk '!a[$0]++' | awk 'NF')
+	printf "$UNMET_DEPS"
+	exit 0
 elif [ -n "$1" ]; then
 	MODE="$1"
 fi
@@ -54,7 +102,7 @@ fi
 # Find target section
 RC_SECTION="$(printf "$RC_LIST" | grep -Pzo "\["$MODE"\]\n?([^\[]+\n?)*" | tr '\0' '\n')"
 if [ -z "$RC_SECTION" ]; then
-	error_message "Unable to execute bspwm section <i>'$MODE'</i>! Section not found."
+	error_message "Unable to execute bspwm section <i>'$MODE'</i>! Section not found." "abort"
 fi
 
 RC_SECTION="$RC_SECTION_BEFR\n$RC_SECTION\n$RC_SECTION_HOST\n$RC_SECTION_AFTR\n"
@@ -63,10 +111,10 @@ ENTRYLIST=""
 for ENTRY in $(printf "$RC_SECTION" | sed '/^$/d; /^\[.*\]$/d'); do
 
 	# Verify entry format
-	SYNTAX_RE="^([-_a-zA-Z1-9]+)\/(((([-._a-zA-Z0-9\*]+)(\([^,\(\)\"\'\`\*]+[^;]\))?),)*((([-._a-zA-Z0-9\*]+)(\([^,\(\)\"\'\`\*]+[^;]\))?)))$"
+	SYNTAX_RE="^([-_a-zA-Z0-9]+)\/(((([-._a-zA-Z0-9\*]+)(\([^,\(\)\"\'\`\*]+[^;]\))?),)*((([-._a-zA-Z0-9\*]+)(\([^,\(\)\"\'\`\*]+[^;]\))?)))$"
 	SYNTAX_ERRORS="$(printf "$ENTRY" | egrep -v "$SYNTAX_RE" | sed '/^$/d')"
 	if ! [ -z "$SYNTAX_ERRORS" ]; then
-		error_message "Syntax error in <i>'rc.conf'</i> on line:\n$SYNTAX_ERRORS"
+		error_message "Syntax error in <i>'rc.conf'</i> on line:\n$SYNTAX_ERRORS" "critical"
 	fi
 
 	# Separate section and modules
@@ -89,11 +137,8 @@ done
 
 RUNLIST=$(printf "$ENTRYLIST" | awk '!a[$0]++' | awk 'NF')
 
-if [ "$1" == "--dry-run" ]; then
-
-	printf "$RUNLIST\n"
-	exit
-
+if [ $CRITICAL_ERROR == 1 ]; then
+	exit 2
 fi
 
 for MOD in $(printf "$RUNLIST"); do
@@ -109,22 +154,38 @@ for MOD in $(printf "$RUNLIST"); do
 
 	if [ -f "$MPATH" ]; then
 
-		if [ ! -x "$MPATH" ]; then		
+		if [ ! -x "$MPATH" ]; then
 			chmod +x "$MPATH"
 		fi
 
+		# Check dependencies
+		if [[ "$CONFIG_DP_CHECK" != "false" ]]; then
+			check_dependencies "$MOD_CMD"
+		fi
+
 		if grep -q "# RC_ASYNC_LOCK" "$MPATH"; then
-			WAIT=$("$MPATH" $MOD_ARGS &> /dev/null&)
-			# printf "S $MPATH $MOD_ARGS\n"
+			if [[ "$1" == "--dry-run" ]]; then
+				printf "S $MPATH $MOD_ARGS\n"
+			elif [[ "$CRITICAL_ERROR" != 1 ]]; then
+				WAIT=$("$MPATH" $MOD_ARGS &> /dev/null&)
+			fi
 		else
-			nohup "$MPATH" $MOD_ARGS &> /dev/null&
-			# printf "A  $MPATH $MOD_ARGS\n"					
+			if [[ "$1" == "--dry-run" ]]; then
+				printf "A $MPATH $MOD_ARGS\n"
+			elif [[ "$CRITICAL_ERROR" != 1 ]]; then
+				nohup "$MPATH" $MOD_ARGS &> /dev/null&
+			fi
 		fi
 
 	else
 
-		error_message "Unable to execute bspwm module <i>'$MOD'</i>! File is missing."
+		error_message "Module <i>'$MOD'</i> is missing." "critical"
 
 	fi
 
 done
+
+if [ $CRITICAL_ERROR == 1 ]; then
+	$MODULES/interface/notify warning "Section <i>'$MODE'</i> will not run until all errors are resolved!"
+	exit 2
+fi
